Extra start values
OhmEnergy/Java-OCA-OCPP pull request #6
Opened 2022-12-05 22:26 UTC by PhilPotter

Introduce inlet export and import values, and serialisation/deserialisation code, as well as a utility function
for easier testing from the server API project.

2022-12-13 17:15 UTC, Amxt commented on ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ClientCoreProfile.java
> +  public StartTransactionRequest createSolarStartTransactionRequest(
this is not specifically for solar, we're reading values from the inlet, there should be no reference to solar

2022-12-13 17:27 UTC, PhilPotter commented on ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ClientCoreProfile.java
> +  public StartTransactionRequest createSolarStartTransactionRequest(
Renamed, thanks.

2022-12-14 08:58 UTC, DanielVocke requested changes
why did you commit the imp file changes? Otherwise looks good.

2022-12-15 18:22 UTC, Amxt approved these changes

2022-12-16 14:21 UTC, Amxt approved these changes

2023-03-02 11:31 UTC, PhilPotter commented
Approved by Dan V verbally, although we will need to remove this code ultimately, due to third-party compatibility reasons.

2023-03-02 11:32 UTC, merged